name: Project Set-up, Formatting, Linting, Building

on:
    pull_request:
        branches: ['**']

jobs:
    build-checks:
        name: Set-up, Lint, Format and Build
        runs-on: ubuntu-latest

        steps:
            - name: Set up Node.js
              uses: actions/checkout@v4
              with:
                  node-version-file: '.nvmrc'

            - name: Install Dependencies
              run: yarn

            - name: Formatting the code
              run: yarn prettier

            - name: Linting the code
              run: yarn lint

            - name: Build project
              run: yarn build
